---

- name: Remove pi user
  user:
    name: pi
    state: absent
  become: true

- name: Add justplayit user
  become: true
  user:
    name: "justplayit"

- name: Install required packages
  package:
    name:
      - git
      - mpd
      - python3-musicpd
      - mpc
  become: true

- name: Make books directory
  file:
    path: "{{ audiobook_dir }}"
    state: directory
    mode: "0777"
  become: true

- name: Copy example books into it
  copy:
    src: "audiobooks/"
    dest: "{{ audiobook_dir }}"

- name: Clone justplayit git repo
  git:
    repo: https://github.com/spookypeanut/justplayit.git
    dest: "{{ git_checkout_dir }}"

- name: Replace config
  template:
    src: "mpd.conf.j2"
    dest: "/etc/mpd.conf"
  become: true
  notify:
    - restart mpd

- name: Copy service into place
  template:
    src: "justplayit.service.j2"
    dest: "/etc/systemd/system/justplayit.service"
  become: true
  notify:
    - restart justplayit
