---

- name: reload systemctl
  command: systemctl daemon-reload
  become: true

- name: restart mpd
  systemd:
    name: mpd
    enabled: true
    state: restarted
    daemon_reload: true
  become: true

- name: restart justplayit
  systemd:
    name: justplayit
    enabled: true
    state: restarted
    daemon_reload: true
  become: true
