---

- name: "Minimal prep of a brand new rpi, to work with the main playbook"
  hosts: new_pi
  vars_files:
    - new_user.yml
  vars:
    new_hostname: audiobooks
  roles:
    - role: raspberrypi-prep
      become: true
